#   docker compose up --build      # sobe tudo
#   docker compose down            # encerra tudo
services:
# Gerador de dados estáticos
  data-generator:
    image: python:3.11-slim
    container_name: data-generator
    volumes:
      - ./data:/data
      - ./scripts:/scripts  
    command: >
      sh -c "if [ ! -f /data/flights_db.json ] || [ ! -f /data/hotels_db.json ]; then 
        echo 'Base não encontrada ou incompleta. Gerando novos dados...'; 
        python /scripts/generate_data.py; 
      else 
        echo 'Base de dados já existe. Pulando geração.'; 
      fi"

# Sobe a stack gRPC completa: FlightService (A), HotelService (B), Gateway (P) e frontend.

  flight:
    build: ./a
    container_name: flight-service
    expose:
      - "50051"
    volumes:
      - ./data:/data
    depends_on:
      data-generator:
        condition: service_completed_successfully
      
  hotel:
    build: ./b
    container_name: hotel-service
    expose:
      - "50052"
    volumes:
      - ./data:/data
    depends_on:
      data-generator:
        condition: service_completed_successfully

  gateway:
    build:
      context: .
      dockerfile: p/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      # Endereços dos serviços gRPC pelos nomes de serviço da rede do compose.
      FLIGHT_SERVICE_ADDRESS: static://flight:50051
      HOTEL_SERVICE_ADDRESS: static://hotel:50052
    depends_on:
      - flight
      - hotel

# Stack REST

  flight-rest:
      build: ./a_rest
      container_name: flight-service-rest
      ports:
        - "5001:5001"
      volumes:
        - ./data:/data
      depends_on:
        data-generator:
          condition: service_completed_successfully

  hotel-rest:
      build: ./b_rest
      container_name: hotel-service-rest
      ports:
        - "5002:5002"
      volumes:
        - ./data:/data
      depends_on:
        data-generator:
          condition: service_completed_successfully

  gateway-rest:
      build:
        context: .
        dockerfile: p_rest/Dockerfile 
      container_name: gateway-rest
      ports:
        - "9080:9080"  # Exposto na porta 9080 para não conflitar com a gRPC (8080)
      environment:
        FLIGHT_SERVICE_REST_URL: http://flight-rest:5001/api/flights
        HOTEL_SERVICE_REST_URL: http://hotel-rest:5002/api/hotels
        SPRING_CODEC_MAX_IN_MEMORY_SIZE: 10MB
      depends_on:
        - flight-rest
        - hotel-rest


  frontend:
      build: ./hclient
      container_name: hclient
      ports:
        - "5500:80"
      depends_on:
        - gateway
