# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import travel_pb2 as travel__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in travel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightServiceStub(object):
    """=============================================================================
    2) FlightService — Módulo A (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFlights = channel.unary_unary(
                '/travel.v1.FlightService/SearchFlights',
                request_serializer=travel__pb2.FlightSearchRequest.SerializeToString,
                response_deserializer=travel__pb2.FlightSearchResponse.FromString,
                _registered_method=True)
        self.StreamFlights = channel.unary_stream(
                '/travel.v1.FlightService/StreamFlights',
                request_serializer=travel__pb2.FlightSearchRequest.SerializeToString,
                response_deserializer=travel__pb2.Flight.FromString,
                _registered_method=True)


class FlightServiceServicer(object):
    """=============================================================================
    2) FlightService — Módulo A (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    def SearchFlights(self, request, context):
        """Busca padrão: uma requisição, uma resposta com a lista completa. (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFlights(self, request, context):
        """Streaming do servidor: envia voo a voo conforme encontrados.
        Útil quando o catálogo é grande e queremos exibir resultados parciais.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFlights,
                    request_deserializer=travel__pb2.FlightSearchRequest.FromString,
                    response_serializer=travel__pb2.FlightSearchResponse.SerializeToString,
            ),
            'StreamFlights': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFlights,
                    request_deserializer=travel__pb2.FlightSearchRequest.FromString,
                    response_serializer=travel__pb2.Flight.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel.v1.FlightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel.v1.FlightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightService(object):
    """=============================================================================
    2) FlightService — Módulo A (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    @staticmethod
    def SearchFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel.v1.FlightService/SearchFlights',
            travel__pb2.FlightSearchRequest.SerializeToString,
            travel__pb2.FlightSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/travel.v1.FlightService/StreamFlights',
            travel__pb2.FlightSearchRequest.SerializeToString,
            travel__pb2.Flight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HotelServiceStub(object):
    """=============================================================================
    3) HotelService — Módulo B (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchHotels = channel.unary_unary(
                '/travel.v1.HotelService/SearchHotels',
                request_serializer=travel__pb2.HotelSearchRequest.SerializeToString,
                response_deserializer=travel__pb2.HotelSearchResponse.FromString,
                _registered_method=True)
        self.BulkSearchHotels = channel.stream_unary(
                '/travel.v1.HotelService/BulkSearchHotels',
                request_serializer=travel__pb2.HotelSearchRequest.SerializeToString,
                response_deserializer=travel__pb2.HotelSearchResponse.FromString,
                _registered_method=True)


class HotelServiceServicer(object):
    """=============================================================================
    3) HotelService — Módulo B (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    def SearchHotels(self, request, context):
        """Busca padrão. (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkSearchHotels(self, request_iterator, context):
        """Streaming do cliente: o gateway pode enviar várias buscas (ex.: várias
        cidades de uma vez) e receber uma resposta agregada ao final.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchHotels': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHotels,
                    request_deserializer=travel__pb2.HotelSearchRequest.FromString,
                    response_serializer=travel__pb2.HotelSearchResponse.SerializeToString,
            ),
            'BulkSearchHotels': grpc.stream_unary_rpc_method_handler(
                    servicer.BulkSearchHotels,
                    request_deserializer=travel__pb2.HotelSearchRequest.FromString,
                    response_serializer=travel__pb2.HotelSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel.v1.HotelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel.v1.HotelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelService(object):
    """=============================================================================
    3) HotelService — Módulo B (TypeScript/Node)
    Aplicação principal (B.2)
    =============================================================================

    """

    @staticmethod
    def SearchHotels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel.v1.HotelService/SearchHotels',
            travel__pb2.HotelSearchRequest.SerializeToString,
            travel__pb2.HotelSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkSearchHotels(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/travel.v1.HotelService/BulkSearchHotels',
            travel__pb2.HotelSearchRequest.SerializeToString,
            travel__pb2.HotelSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TravelPackageServiceStub(object):
    """=============================================================================
    4) TravelPackageService — Módulo P (Java/Spring Boot)
    Aplicação principal (B.2)

    Exposto internamente para fins de teste/demonstração; o browser fala REST
    com P. Mantém apenas a chamada unary principal — a demonstração de
    bidirectional streaming exigida pelo item B.1 fica no ChatService logo
    abaixo, como exemplo isolado (o fluxo de busca de pacotes não tem encaixe
    natural para bidi).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchPackages = channel.unary_unary(
                '/travel.v1.TravelPackageService/SearchPackages',
                request_serializer=travel__pb2.PackageSearchRequest.SerializeToString,
                response_deserializer=travel__pb2.PackageSearchResponse.FromString,
                _registered_method=True)


class TravelPackageServiceServicer(object):
    """=============================================================================
    4) TravelPackageService — Módulo P (Java/Spring Boot)
    Aplicação principal (B.2)

    Exposto internamente para fins de teste/demonstração; o browser fala REST
    com P. Mantém apenas a chamada unary principal — a demonstração de
    bidirectional streaming exigida pelo item B.1 fica no ChatService logo
    abaixo, como exemplo isolado (o fluxo de busca de pacotes não tem encaixe
    natural para bidi).
    =============================================================================

    """

    def SearchPackages(self, request, context):
        """Busca principal do usuário: P consulta A e B em paralelo, combina e ordena.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TravelPackageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPackages,
                    request_deserializer=travel__pb2.PackageSearchRequest.FromString,
                    response_serializer=travel__pb2.PackageSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel.v1.TravelPackageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel.v1.TravelPackageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TravelPackageService(object):
    """=============================================================================
    4) TravelPackageService — Módulo P (Java/Spring Boot)
    Aplicação principal (B.2)

    Exposto internamente para fins de teste/demonstração; o browser fala REST
    com P. Mantém apenas a chamada unary principal — a demonstração de
    bidirectional streaming exigida pelo item B.1 fica no ChatService logo
    abaixo, como exemplo isolado (o fluxo de busca de pacotes não tem encaixe
    natural para bidi).
    =============================================================================

    """

    @staticmethod
    def SearchPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel.v1.TravelPackageService/SearchPackages',
            travel__pb2.PackageSearchRequest.SerializeToString,
            travel__pb2.PackageSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub(object):
    """=============================================================================
    5) ChatService — Demonstração isolada (item B.1 do enunciado)

    Por que está aqui:
    O item B.1 exige os 4 tipos de comunicação gRPC. Os outros 3 (unary,
    server-streaming e client-streaming) já são exercitados naturalmente
    pelos serviços da aplicação principal (acima). O quarto tipo
    (bidirectional) não tem encaixe natural no fluxo de busca de pacotes,
    e o enunciado permite "exemplos isolados". Optamos pelo caso clássico
    de chat em tempo real, que é enxuto e fácil de demonstrar.

    Implementação sugerida:
    Um cliente e um servidor pequenos, em qualquer linguagem da stack,
    apenas para gerar prints da execução e incluir no relatório.
    NÃO faz parte da aplicação principal.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/travel.v1.ChatService/Chat',
                request_serializer=travel__pb2.ChatMessage.SerializeToString,
                response_deserializer=travel__pb2.ChatMessage.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """=============================================================================
    5) ChatService — Demonstração isolada (item B.1 do enunciado)

    Por que está aqui:
    O item B.1 exige os 4 tipos de comunicação gRPC. Os outros 3 (unary,
    server-streaming e client-streaming) já são exercitados naturalmente
    pelos serviços da aplicação principal (acima). O quarto tipo
    (bidirectional) não tem encaixe natural no fluxo de busca de pacotes,
    e o enunciado permite "exemplos isolados". Optamos pelo caso clássico
    de chat em tempo real, que é enxuto e fácil de demonstrar.

    Implementação sugerida:
    Um cliente e um servidor pequenos, em qualquer linguagem da stack,
    apenas para gerar prints da execução e incluir no relatório.
    NÃO faz parte da aplicação principal.
    =============================================================================

    """

    def Chat(self, request_iterator, context):
        """Fluxos simultâneos nos dois sentidos: cliente envia mensagens conforme
        o usuário digita; servidor envia mensagens recebidas de outros usuários
        sem aguardar a próxima requisição do cliente.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=travel__pb2.ChatMessage.FromString,
                    response_serializer=travel__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """=============================================================================
    5) ChatService — Demonstração isolada (item B.1 do enunciado)

    Por que está aqui:
    O item B.1 exige os 4 tipos de comunicação gRPC. Os outros 3 (unary,
    server-streaming e client-streaming) já são exercitados naturalmente
    pelos serviços da aplicação principal (acima). O quarto tipo
    (bidirectional) não tem encaixe natural no fluxo de busca de pacotes,
    e o enunciado permite "exemplos isolados". Optamos pelo caso clássico
    de chat em tempo real, que é enxuto e fácil de demonstrar.

    Implementação sugerida:
    Um cliente e um servidor pequenos, em qualquer linguagem da stack,
    apenas para gerar prints da execução e incluir no relatório.
    NÃO faz parte da aplicação principal.
    =============================================================================

    """

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/travel.v1.ChatService/Chat',
            travel__pb2.ChatMessage.SerializeToString,
            travel__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
